// Resolved via pnpm workspace install (`pnpm install`).
import { rm } from 'node:fs/promises';
import path from 'node:path';
import { defineConfig, type Plugin } from 'vite';

import { currentTree, releaseSegment, RELEASE_ENTRIES } from './scripts/release.ts';

/**
 * The tree this build writes: the deployable tree of the selected release channel
 * (`DPK_CHANNEL`), or the development tree when `pnpm dev` sets
 * `DPK_ASSETS_DIR=public-dev` — a deploy build must not be able to change what a
 * running dev session serves (see `scripts/release.ts`).
 */
const tree = currentTree();

/**
 * The `VERSION` file is the marker that a release finished assembling, and
 * `isCompleteRelease` (scripts/assemble-assets.ts) trusts it. Vite writes the
 * bundle straight into the release directory, so the marker has to be dropped
 * before the first byte is written: an interrupted build must not leave a
 * truncated bundle next to a marker that claims the release is complete.
 *
 * `scripts/assemble-assets.ts` writes the marker again once the release content is
 * in place.
 *
 * The marker is located from Vite's *resolved* output directory rather than from
 * the current working directory, so it follows wherever this build actually writes
 * (a caller that sets `root` or `build.outDir` included).
 */
const invalidateReleaseMarker = (): Plugin => {
  let marker: string | null = null;
  return {
    name: 'dev-process-kit:invalidate-release-marker',
    configResolved(config) {
      // Vite lets `rollupOptions.output.dir` override the output directory it
      // computed. The bundle URL shape is a published contract, so an override is a
      // configuration error rather than something to work around: silently
      // invalidating a marker elsewhere would let a release be rewritten without
      // losing its "complete" marker.
      const output = config.build.rollupOptions.output;
      const dirs = (Array.isArray(output) ? output : [output]).map((entry) => entry?.dir);
      if (dirs.some((dir) => dir !== undefined)) {
        throw new Error(
          'dev-process-kit: `build.rollupOptions.output.dir` overrides the asset layout; the bundle has to be written to `build.outDir`.',
        );
      }
      marker = path.resolve(config.root, config.build.outDir, 'VERSION');
    },
    async buildStart() {
      if (marker !== null) await rm(marker, { force: true });
    },
  };
};

/**
 * The framework ships as a build-free ESM bundle per entry point, whose URL shape mirrors
 * the pinned asset URL: `<origin>/dev-process-kit@<version>/<entry>.js`
 * (`scripts/release.ts` owns the entry list). The entries share the core, the components
 * and their dependencies, which Rollup emits once as chunks next to them.
 *
 * The asset trees are build output, not source directories: `src/**` is the
 * source of truth and the tree around this bundle is assembled from it.
 */
export default defineConfig({
  define: {
    __ARTIFACT_FRAMEWORK_VERSION__: JSON.stringify(tree.frameworkVersion),
  },
  plugins: [invalidateReleaseMarker()],
  // The asset directory is generated by the build; never treat it as Vite's
  // static-file source.
  publicDir: false,
  build: {
    outDir: `${tree.assetsDir}/${releaseSegment(tree.releaseId)}`,
    // A published release is rebuilt as a whole: a chunk left over from an earlier build
    // would ship without being referenced, and `scripts/minify-release.ts` would re-minify
    // it on every build, so the tree would never be reproducible. The dev tree is kept,
    // because `vite build --watch` rewrites it under a running dev session.
    emptyOutDir: tree.channel !== 'dev',
    copyPublicDir: false,
    target: 'es2022',
    minify: 'esbuild',
    // A release is distributed, so it carries no source map (see `scripts/release.ts`);
    // only the development tree, which is never deployed, keeps one.
    sourcemap: tree.sourcemap,
    // Attribution for the packages that actually end up in the bundles. Vite walks
    // the Rollup module graph, so this cannot list a dependency whose code was
    // tree-shaken away, nor miss one that a dependency pulled in transitively.
    // `THIRD_PARTY_LICENSES.md` is emitted into the release directory next to the
    // bundle, which is what makes it immutable-cacheable and self-contained.
    license: { fileName: 'THIRD_PARTY_LICENSES.md' },
    lib: {
      entry: RELEASE_ENTRIES,
      formats: ['es'],
      fileName: (_format, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      output: {
        // The entries import shared code from this directory. A release is mirrored as a
        // whole, so the chunk names only have to be stable within one release, and nothing
        // but the entries is a contract: the names say "internal" rather than pretending to
        // describe what Rollup decided to share.
        chunkFileNames: 'chunks/shared-[hash].js',
      },
    },
  },
});
