#!/usr/bin/env node
/**
 * Verifies that no published release was changed or deleted.
 *
 * The distribution ADR says a version directory is immutable once published: a fix is a new
 * version. This compares the deployable tree with a base revision and fails when a release
 * that existed there has changed — modified, added to, renamed or deleted. A *new* release
 * directory is what publishing means and passes, and the debug release is overwritten in
 * place by design, so it is not a published version either.
 *
 * Usage:
 *   node scripts/verify-published.ts <base-ref>     # origin/main, HEAD~1, a sha, …
 *
 * CI passes the base of the change (`github.event.pull_request.base.sha` for a pull request,
 * `github.event.before` for a push), which needs the base revision to be fetched
 * (`actions/checkout` with `fetch-depth: 0`).
 */
import { execFileSync } from 'node:child_process';

import { DEBUG_RELEASE_ID, publishTree, releaseSegment } from './release.ts';

/** Repository root, resolved from this file's own location (`scripts/`). */
const root = `${import.meta.dirname}/..`;
const assetsDir = publishTree('stable').assetsDir;
const base = process.argv[2];

if (base === undefined) {
  console.error('usage: node scripts/verify-published.ts <base-ref>');
  process.exit(2);
}

// The first push of a branch has no previous revision to compare against.
if (/^0*$/.test(base)) {
  console.log(`✔ no base revision to compare with (first push of the branch)`);
  process.exit(0);
}

const git = (...args: readonly string[]): string =>
  execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trimEnd();

/** `<status>\t<path>[\t<path>]` lines of the tree between the base and HEAD. */
const changed = (): string[] | null => {
  try {
    return git('diff', '--name-status', `${base}...HEAD`, '--', assetsDir)
      .split('\n')
      .filter((line) => line !== '');
  } catch {
    return null;
  }
};

/** Whether a release was already published at the base revision. */
const publishedAtBase = (release: string): boolean => {
  try {
    execFileSync('git', ['cat-file', '-e', `${base}:${assetsDir}/${releaseSegment(release)}/VERSION`], {
      cwd: root,
      stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
};

const lines = changed();
if (lines === null) {
  console.error(`✗ cannot diff ${base}...HEAD (is the base revision fetched? try \`git fetch\`)`);
  process.exit(1);
}

const RELEASE_PATH = new RegExp(`^${assetsDir}/dev-process-kit@([^/]+)/`);
const violations: string[] = [];
for (const line of lines) {
  const [status = '', ...paths] = line.split('\t');
  for (const path of paths) {
    const release = RELEASE_PATH.exec(path)?.[1];
    // The tree's root files (the release index, the headers, the licence) are regenerated by
    // every build, and the debug release is overwritten by design.
    if (release === undefined || release === DEBUG_RELEASE_ID) continue;
    if (publishedAtBase(release)) violations.push(`${status} ${path}`);
  }
}

if (violations.length > 0) {
  console.error(`✗ a published release changed since ${base} (${violations.length} path(s)):`);
  for (const line of violations.slice(0, 20)) console.error(`  ${line}`);
  if (violations.length > 20) console.error(`  … and ${violations.length - 20} more`);
  console.error('  A published version is immutable: publish the fix as a new version instead.');
  process.exit(1);
}

console.log(`✔ no published release changed since ${base} (${lines.length} changed path(s) checked)`);
